### ISSUE TITLE
src/projection.c:19:18: error: variable ‘z’ set but not used [-Werror=unused-but-set-variable]    19 |         double  *z;

### ISSUE THREAD

**Issue by vkinnune** [kujtimsadiku/fdf#1]
Does not compile on linux
![pic-selected-220519-1459-02](https://user-images.githubusercontent.com/96283427/169288631-a43809b4-c061-45d1-bc55-4b589346177a.png)

**Comment by kujtimsadiku** [comment]
Thanks for the seeing unused variable.
